### ISSUE TITLE
Implement `Serialize` for `Value`

### ISSUE THREAD

**Issue by tqwewe** [PSeitz/serde_json_borrow#3]
Value doesn't seem to implement Serialize, but does implement Deserialize. Is there a reason for this? It would be handy to be able to serialize the value, since serializing doesn't need ownership of a value typically.

**Comment by PSeitz** [comment]
I started it but discontinued, since it's a lot of code to adjust and I didn't need it

I pushed the current (broken) state to the `add_serialization` branch, if you want to continue
https://github.com/PSeitz/serde_json_borrow/blob/add_serialization/src/ser.rs

Or start over from https://github.com/serde-rs/json/blob/master/src/value/ser.rs
